### ISSUE TITLE
PHP 8.2.0

### ISSUE THREAD

**Issue by YoannQueret** [fgrosse/PHPASN1#100]
Hi !
Think the changes from php 8.1.0 to 8.2.0 have no impact .. ?
Can you add PHP 8.2.0 support? Especially in composer.json?
Y

**Comment by athompson-merlin** [comment]
Sadly, this will be an issue with every single LibreNMS install whose OS packages just autoupgraded to PHP 8.2 without warning, at least temporarily.  Signed, Grumpy LibreNMS Admin. :-(
