### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by aztech-dev** [FGrosse/PHPASN1#24]
In order to ease adoption of your library, and so that it can be adopted by other projects, it would be nice to tag/release a version of the project using semantic version (ie. v0.0.1)

In current state, when using your lib through composer, it's not usable by projects that have a minimum stability setting of "stable".

**Comment by FGrosse** [comment]
Done. The old version has the tag 0.9.0 and the new one with PSR-4 autoloading and changed namespaces is 1.0.0.
As always feel free too open new feature requests or bug reports when anything comes up.

Best regards
Friedrich

**Comment by FGrosse** [comment]
Additional info: I am not yet maintainer of the packagist repo so I can not set up the service hook or force an update of the package in order for the tagged version to become visible there. However this should hopefully be the case soon (waiting for feedback on #25)

**Comment by FGrosse** [comment]
Okay now everything should be fine on https://packagist.org/packages/fgrosse/phpasn1

**Comment by aztech-dev** [comment]
Great, thanks a lot... definitely makes it easier with tagged versions :)
