### ISSUE TITLE
Encode context-specific objects

### ISSUE THREAD

**Issue by aztech-dev** [FGrosse/PHPASN1#29]
The library can currently parse context-specific objects, but it's not possible to create them. 

I'm using https://github.com/mdanter/phpecc/blob/master/src/Serializer/Util/ASN/ASNContext.php to generate those in another project, but I am not sure this is not the best approach.

**Comment by aztech-dev** [comment]
My gut feeling tells me that it's basically encoded as an identifier with the class bits (7-8) set to 0x02 (ref https://github.com/FGrosse/PHPASN1/blob/master/lib/ASN1/Identifier.php#L30-L44), the P/C bit set to 0x0, and the tag bits containing the context index. 

I may be wrong, as this is extrapolated from parsing the output of OpenSSL's PEM encoded private keys, but it seems to make sense.

I got some free time today, I'll issue a P/R with a proposal.

**Comment by aztech-dev** [comment]
So I got this so far : https://github.com/aztech-digital/php-asn1/commit/a6c94be54feaa38fd7ec995400ead6d1f8d084be

But I'm hitting on wall on parsing those back, as your SAN extension use hard-coded identifier values, it seems to conflict with them. Looking at [RFC 5280 ¤ 4.2.16](http://tools.ietf.org/html/rfc5280#section-4.2.1.6), it looks like they also use context specific tags, which may explain the [mystery identifiers](https://github.com/FGrosse/PHPASN1/blob/master/lib/X509/SAN/DNSName.php#L27) ...

**Comment by FGrosse** [comment]
I finally had some time looking over the specs for context specific objects. As far as I understood every ASN.1 object can be marked as context specific (not only constructed objects).

Context specific tags are used to make it possible to decode a received ASN.1 object where several adjacent child objects  may be optional. In this case each object definition gets a tag which is used in the encoding as context specific identifier. In that case it is upon the decoding party to know what a context specific tag means exactly (for example tag [1] is defined to be the name which is a PrintableString or tag [4] is the email address which also happens to be a PrintableString etc..)

I will extend your PR #30 based on this information and would prefer to continue the discussion right there if you don't mind.

Best regards
Friedrich
