### ISSUE TITLE
Would you consider switching to a more permissive license?

### ISSUE THREAD

**Issue by kgilden** [FGrosse/PHPASN1#31]
Hey, just stumbled upon Your library and it looks really polished, kudos!

I would be happy to contribute to the project. Been thinking of the following stuff:

* more complete classes for [X.509](https://tools.ietf.org/html/rfc2459#appendix-A);
* full set of classes for [OCSP](https://tools.ietf.org/html/rfc2560#appendix-B);
* perhaps have a parser to generate PHP classes from ASN.1 specifications;

Unfortunately I'm a little bit concerned by the GPLv3 license preventing the use of this library by most commercial endeavors. Would You ever consider something more permissive, say MIT or Apache2?

**Comment by FGrosse** [comment]
Hey there, I am always happy about people contributing :)

I just never thought too hard about the whole license thing until this point, so thanks for bringing up the topic. After reading through then differences of MIT, Apache and GPL I made up my mind to switch to the MIT license.

**Comment by kgilden** [comment]
Awesome! Thanks :)

**Comment by aztech-dev** [comment]
Nice move ! :)
