### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by Spomky** [FGrosse/PHPASN1#34]
Hi,

This library is not compatible with PHP 7 ; I got the following error:
`Cannot use FG\ASN1\Universal\Null as Null because 'Null' is a special class name in /home/travis/build/mdanter/phpecc/vendor/fgrosse/phpasn1/lib/ASN1/Object.php on line 28`

I think it could be easy to reach compatiblity, but it requires to rename some classes and bump to a major release.

Do you think it could be possible to update this library in this way?

**Comment by aztech-dev** [comment]
You can open an issue or a pull request against the repo if you want to do the changes, @fgrosse will probably be happy to fix/merge the changes
