### ISSUE TITLE
Creating ExplicitlyTaggedObject with huge tags gives surprising results

### ISSUE THREAD

**Issue by FGrosse** [FGrosse/PHPASN1#36]
I dont quite understand why we missed this in #33 but choosing  big integers as tags for `ExplicitlyTaggedObject` breaks.

The issue is effectivly caused by [Base128][1]
I already added a failing (but currently skipped) test to master:

```php
public function testFromBinaryWithHugeTagNumber()
{
    $originalStringObject = new PrintableString('test');
    $originalObject = new ExplicitlyTaggedObject(0xDEADBEEF, $originalStringObject);
    $binaryData = $originalObject->getBinary();

    $parsedObject = ExplicitlyTaggedObject::fromBinary($binaryData);
    $this->assertEquals($originalObject, $parsedObject);
}
```

Environment:
```bash
fgrosse@argp ➤ php --version
PHP 5.6.6 (cli) (built: Feb 19 2015 13:46:45) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.1, Copyright (c) 2002-2015, by Derick Rethans

fgrosse@argp ➤ php -r "echo PHP_INT_SIZE;"
fgrosse@argp ➤ 4
```

[1]: https://github.com/FGrosse/PHPASN1/blob/8fa1bb1c13952470f1a628b086a1944d8882e66c/lib/ASN1/Base128.php#L19

**Comment by FGrosse** [comment]
The expected tag would be `3735928559` but the actual tag is `111`

The problem starts when the following code is executed in `Base128::decode`

```php
public static function encode($value) // value is 3735928559
{
    $octets = chr($value & 0x7F);
    $value >>= 7;
    // value is now -4367491
    ...
}
```

**Comment by kgilden** [comment]
@FGrosse I could take a look tomorrow evening.

**Comment by FGrosse** [comment]
@kgilden would be much appreciated if you have the time

**Comment by kgilden** [comment]
@FGrosse I think I know what's going on. Integers in PHP are always signed. So `0xDEADBEEF` gets automatically promoted to a float. And that messes things up. So on 32bit PHP builds the maximum tag is `PHP_MAX_INT`, or 2,147,483,647.

Theoretically it would be possible to encode such a value, but instead of `0xDEADBEEF` it should be represented as `-0x21524111`. However, there's already a check in place to not allow negative integers [here](https://github.com/FGrosse/PHPASN1/blob/master/lib/ASN1/Identifier.php#L91).

So yeah, I think a check should be added to the [base128 encoding method]. That would make things more explicit. I'm not sure about negative integers though. They should also be off the limits probably.

Hope I explained the problem well enough. What do You think?

**Comment by FGrosse** [comment]
Hey @kgilden thanks for your input. I just had some time and think I could hunt down the issue a bit further. As you can see in the [referenced commit][2] I could trace the issue to phps bit shift operator.
Currently I am a bit puzzled by its behaviour and have to do some additional research.

The [manual][1] states:

>  Right shifts have copies of the sign bit shifted in on the left, meaning the sign of an operand is preserved.

I think there might be a bug there since the original value is explicitly positive.
As you can see in `testPhpShiftByDivisionWithLeadingOneBit` we can use division by 2 as a workaround which has really the same semantics but does not lead to the wrong behaviour.

Please have a look at those tests and tell me what you think.

[1]: http://php.net/manual/en/language.operators.bitwise.php
[2]: https://github.com/FGrosse/PHPASN1/commit/afd7940af901628e6974b8e90a7012221afbfa49

**Comment by FGrosse** [comment]
Ah reading further through the documentation I found the following warning:

> Warning: Shifting integers by values greater than or equal to the system long integer width results in undefined behavior. In other words, don't shift more than 31 bits on a 32-bit system, and don't shift more than 63 bits on a 64-bit system.
Use functions from the gmp extension for bitwise manipulation on numbers beyond PHP_INT_MAX.

I guess I will close the issue by throwing an exception if the value exceeds the maximum allowed bits and will add a feature request issue to document that this needs to be implemented using gmp.
