### ISSUE TITLE
Further OCSP Decoding/Encoding Ability

### ISSUE THREAD

**Issue by korusdipl** [fgrosse/PHPASN1#41]
I met your library today, and it's awesome!

However, when I try to deal with an OCSP Response, it seemed standardized timestamps for publishing, next-update or cert-status of an ocsp response were misinterpreted as unknown objects

The following gist was derived from OCTETSTRING from the OCSP Response.
https://gist.github.com/korusdipl/f0c3075cd61cc8d0616c

Hope this improves your script.
Thanks again for building this stuff up! :)

**Comment by fgrosse** [comment]
Thanks for reporting the issue @korusdipl 
I will look into this as soon as I can. Looking at your gist I suspect an issue with decoding the `GeneralizedTime` part

**Comment by fgrosse** [comment]
I just found the issue. Seems like I forgot to add the parsing to `Object::fromBinary`
This fixed version is [`1.3.2`][1]

[1]: https://packagist.org/packages/fgrosse/phpasn1#1.3.2

**Comment by korusdipl** [comment]
Thanks a trillion! I will look into the revised codes :)
