### ISSUE TITLE
OCSP CertStatus Info Again

### ISSUE THREAD

**Issue by korusdipl** [fgrosse/PHPASN1#43]
Thanks for the last update which resolved the generalized time issue.

However, when parsing OCSP Response, it still interprets the cert status data as unknown or unparsable objects. It was tested with the same gist as provided https://github.com/fgrosse/PHPASN1/issues/41 .

According to the RFC6960, the ASN.1 structure of OCSP response should include the following.

CertStatus ::= CHOICE {
       good        [0]     IMPLICIT NULL,
       revoked     [1]     IMPLICIT RevokedInfo,
       unknown     [2]     IMPLICIT UnknownInfo }

   RevokedInfo ::= SEQUENCE {
       revocationTime              GeneralizedTime,
       revocationReason    [0]     EXPLICIT CRLReason OPTIONAL }

https://tools.ietf.org/html/rfc6960#section-4.2.1

Is this non-standard, so you don't support it, or was it not just implemented?
Hope your library can decode and encode these too as I am considering making an OCSP Responder with pure PHP, and your library is a great tool to help me reduce tremendous amount of work.

Thanks.

Additional Reference : https://gist.github.com/korusdipl/eeb27b36efdac5c7045f

**Comment by fgrosse** [comment]
In general OCSP is not in the focus of this API. However I did already start to support some of the structures from the X509 standard so I would not say no in general but I wont make any promises on that.

Since you know the structure of the OCSP Response from [RFC 6960][1] you can already parse it using PHPASN1:

I wrote a little bit of example code for you in [examples/Issue43.php][2] which produces the following output on an example OCSP response:

```
OCSP response status: 0 (Response has valid confirmations)
ResponseType: Basic response (1.3.6.1.5.5.7.48.1.1)
Response (octet string): 30820440305EA120301E311C3009060355040613025255300F06035504031E080054006500730074180F32303135303731363137353432315A302930273012300706052B0E03021A0401010401010201018000180F32303135303731363137353432315A300B06092A864886F70D01010503820101006E41D713A7860CE0A6C9ECA5677D73878B21E398D575E5EEAD8350EDA41A38B859B057B560CC12FED040EF7FF1D7AF9B258D4C596449C6E188C3C811FA044BA0325BC959BBD68E376B4CB2C823FC4BFDF87F80D99D961D075E0EDBFB012DA661AFFB7B751CB1BEB7A40981731803639E5E1F09A2BC17D921617A4636F3B89D14C73E8DBEB5441E55B3D8A134D67FFBA9B7306C7C7C9EED6CFC876CC051BD89E3E6E6C4EC1CFB1BBEC310E597E4BE4B8BFEDE5694B38D95162E9CE038372B5FDA550865B6739C1D1DBD01B8BE6D45F4840472FD55D1A5340FF654F3523B9523E53C4BFF0CC4C4A35BDE3D366F1AFF12D4AFA47830FF6DFC0CDB677AEB755F9ADFA08202CA308202C6308202C2308201ACA003020102020101300B06092A864886F70D010105301E311C3009060355040613025255300F06035504031E080054006500730074301E170D3133303230313030303030305A170D3136303230313030303030305A301E311C3009060355040613025255300F06035504031E08005400650073007430820122300D06092A864886F70D01010105000382010F003082010A0282010100B05973FF7CA59A4FBCB8FE3FC7AD54581962A96D3CFF58CC03CDD08F6CAE080BE13219AEABC06FC963F88E75E8C53CB78936450D7223E558361651D69DAD1332C5398E59AFF16FE6BBD537FAAEE2D7EDF7F49AC4664AC32CD0E9276DE0A8A0600B539A347EFEBE2701466A0FE648F65FAD9731A293E53305059CD3B5217B21A523B7D4955D08C6DDA1C8CBB0F598ECA9BC4C382D24BE46FBC94DECD241E0A82E95FB1F38919E85543642566472F6C06E6B6FF489CE95F01E445AED1DB9D2F37C4C5B524ACA78617CCAE9A92CFEA931449D549012D40199516AC503FB3BBC8324C8CF4B0D805ACEB71F043B38D946227FBC18953A7F3C06B7F88B40FE7D55E6250203010001A30F300D300B0603551D0F040403020002300B06092A864886F70D01010503820101005FB9B28F4EF9831AB0F1A2A09B3F01683D10B4493C0F2F6195F1FE6C0FF49BC9CD0DA097728143B60EFAAE1869F9E942427CBA35BBA0E7E33BAE0ECDE6EA27FCE874E901FF59DDAEF6A24D93A2BFCD17062DFAF0CEAC56391786D70D991FBB8CEE0CB9A3A63DBA0E4E2D7B7055A21B0B4D76EF2796BF4D3D956A7C0D3B2C7CE655CFC72DD5F11AF50309661D9A330C36D419B7BF9E850324280C8EF68A2AF2F2908848716FA0E96ED239C2917E5C391FC9330EFF35E9714E0D20B75F5530A37695CBD76EFF4987FA0E07BF2555A653BDD2D7681C3D601D4319C2E7A7E1D6D3CE15AFE1DB4B15E95633994659B2C45A7EE426085C960231BF5D27906C9FAE8C2D
```

Please note that this does no propper error handling and all. In general I would advise an approach that defines the whole structure as a class. Have a look at the [X509 implementations][3].

[1]: https://tools.ietf.org/html/rfc6960#section-4.2.1
[2]: https://github.com/fgrosse/PHPASN1/blob/master/examples/Issue43.php
[3]: https://github.com/fgrosse/PHPASN1/tree/master/lib/X509

**Comment by korusdipl** [comment]
Thanks for the advice.
I will look into it.
