### ISSUE TITLE
PHP 5.4 and 5.5

### ISSUE THREAD

**Issue by Spomky** [fgrosse/PHPASN1#53]
Hi,

I noted that you tagged v1.4.0 yesterday.
This new release adds cool stuf, but you dropped PHP 5.4 and 5.5 that are still maintained (security support).

What are the reasons that I missed for that choice?

**Comment by afk11** [comment]
I missed this also. PHP5.6 seems too high for the minimum.. Guessing this could be because of ::class?

**Comment by aztech-dev** [comment]
::class is 5.5 no ? and, 5.4 is due to EOL in 26 days... so it should not be an issue with ::class

**Comment by afk11** [comment]
I started digging some more! Will update as I go. 

https://github.com/fgrosse/PHPASN1/blob/master/lib/ASN1/Construct.php#L27 `...` after comment in constructor?

**Comment by aztech-dev** [comment]
http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list

That's 5.6, can be mocked by func_get_args() and variants

**Comment by fgrosse** [comment]
I wanted to move to a recent php version for a long time now and yesterday I decided to go for it and see what happens. Initially I planned to move to a minimum of PHP 5.5 but then thought that if I am going to raise minimum requirements I can go all the way to 5.6 now.

PHP 5.6 has been around for a year now. It is faster and has more features. PHP 7 will probably come very soon (scheduled for November this year afaik). If we keep supporting old PHP versions it takes forever to profit from newer language features (variadics, generators,, etc). 

So thats my reasoning, I could be convinced to downgrade to 5.5 again if this imposes a real issue for you but I would rather push people to upgrade PHP instead. What do you think?

**Comment by Spomky** [comment]
OK I understand your point of view. @aztech-dev is also right when he wrote that PHP 5.4 is EOL.
But last merged PR or features added are compatible with PHP 5.5 for example.

What do you think if we create a branch tagged v1.3.2 for backward compatibility only that includes these features? This branch will be abandonned when PHP 5.5 is no longer supported (i.e. mid-2016)

**Comment by fgrosse** [comment]
I think that would be a good solution. I will do this the comming week

**Comment by fgrosse** [comment]
I just finally found the time to create the [compat/php5-5 branch][1].
On composer you can require it using [dev-compat/php5-5][2]

I hope this works for all uf us now. However I will make no promises that new features will always also be mreged into the compatibility branch.

[1]: https://github.com/FGrosse/PHPASN1/tree/compat/php5-5
[2]: https://packagist.org/packages/fgrosse/phpasn1#dev-compat/php5-5

**Comment by fgrosse** [comment]
I created [this google group/mailing list][1] in order to have some space where such changes as the version change can be discussed in the future.

Next time I want to introduce some incomaptible changes we can talk about it first there so we can avoid any big suprises in the future.

Feel invited @Spomky @afk11 @aztech-dev :)
Documentation on the th README.md will folllow as well

[1]: https://groups.google.com/d/forum/phpasn1
