### ISSUE TITLE
Add keywords to composer.json

### ISSUE THREAD

**Issue by dol** [fgrosse/PHPASN1#60]
When searching for 'asn1' on packagist.org the PHPASN1 library is not found => https://packagist.org/search/?q=asn1

To fix this problem I suggest to add some [keywords](https://getcomposer.org/doc/04-schema.md#keywords) to the composer.json.
An example is the phpseclib project: https://packagist.org/packages/phpseclib/phpseclib

**Comment by fgrosse** [comment]
Thanks for the suggestion :)
