### ISSUE TITLE
NullObject is undefined

### ISSUE THREAD

**Issue by jk204** [fgrosse/PHPASN1#61]
In the example provided in the readme page, the object FG\Universal\NullObject is used. Does this object exists? Should it be replaced by FG\Universal\Null?

**Comment by fgrosse** [comment]
Could it be you are using and old version of PHPASN? The file [exists in the current HEAD of master][1].
The older [Null][2] class does also still exist but was deprecated because this is no longer a valid name in php7.

[1]: https://github.com/fgrosse/PHPASN1/blob/27181c72dcaeef9046925a4a2bf75a68b98f6dfb/lib/ASN1/Universal/NullObject.php
[2]: https://github.com/fgrosse/PHPASN1/blob/27181c72dcaeef9046925a4a2bf75a68b98f6dfb/lib/ASN1/Universal/Null.php

**Comment by fgrosse** [comment]
I also tried out the example myself and added the source code to [examples/readmeExample.php][1]. It all works fine as far as I can tell.

```bash
fgrosse@localhost:~/Workspace/PHPASN1/examples [master*] ➤ php readmeExample.php
MBgCAwHiQAEB/woBARYLSGVsbG8gd29ybGQxODAYAgMB4kABAf8KAQEWC0hlbGxvIHdvcmxkBQAGBiqBegEQCQYJKoZIhvcNAQEBEwdGb28gYmFy%
```

[1]: https://github.com/fgrosse/PHPASN1/blob/7c2d5cad32bbd14ce5ceb2224cf32e09704be655/examples/readmeExample.php

**Comment by jk204** [comment]
thank you for your quick response. I will check versions and namespaces. I just installed it this week through composer and ran the test example in the readme file. 

I will be using your project to implement a SIM profile creator accoding to this specification: http://simalliance.org/euicc/euicc-technical-releases/
Regards,
Martin
 


    Le Samedi 5 décembre 2015 11h24, Friedrich Große <notifications@github.com> a écrit :
 

 Could it be you are using and old version of PHPASN? The file exists in the current HEAD of master.
The older Null class does also still exist but was deprecated because this is no longer a valid name in php7.—

**Comment by fgrosse** [comment]
Nice to hear what people are actually using this for. When/if you put this on github let me know :)

FYI: The most recent stable version is [1.5.1][1]. In case you have questions you can also use the [mailing list][2] if you want.

[1]: https://packagist.org/packages/fgrosse/phpasn1#1.5.1
[2]: https://groups.google.com/d/forum/phpasn1
