### ISSUE TITLE
Doesn't detect gmp

### ISSUE THREAD

**Issue by nportik-sugarcrm** [fgrosse/PHPASN1#71]
ISSUE:
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fgrosse/phpasn1 1.5.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - fgrosse/phpasn1 1.5.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - Installation request for fgrosse/phpasn1 1.5.3 -> satisfiable by fgrosse/phpasn1[1.5.3].

PHPINFO OUTPUT:
gmp support | enabled
-- | --
GMP version | 6.1.2

SYSTEM: OS HIGH SIERRA
I have installed php71 and php71-gmp. php.ini has gmp extension enabled

**Comment by afk11** [comment]
This is likely a system configuration issue, so I'm not sure how to help here. I found this issue https://github.com/composer/composer/issues/5749, which seems to have a few tips for debugging this.. hope it helps

**Comment by nportik-sugarcrm** [comment]
Hi @afk11 ! Thank you for the heads up, indeed it was a system config/setup issue.

What I had to do was:
1. find the path of that one php.ini which gets really loaded (run in terminal: php --ini) - I have several php.ini's
2. At the specified location (in my case /etc/), you have to have a php.ini (or create one based on the php.ini.default)
3. Enable gmp module by adding as an extenstion (in my case:`extension=/usr/local/Cellar/php71-gmp/7.1.14_19/gmp.so`)

Now everything works as intended. Sorry for the trouble @afk11 .

**Comment by afk11** [comment]
Awesome, glad to hear it was sorted out!
